<?php
/**
 * Align WordPress AI “Generate featured image” imports with SIM attachment rules.
 *
 * WP AI’s default path uses a creative prompt for the filename, dumps a
 * “Generated by … Prompt: …” description, sideloads with post_parent = 0
 * (Unattached), and only sets featured_media in the editor draft (no save).
 * This compat layer rewrites title/slug/filename/parent to match the
 * on-demand generation plan (focus keyword → title/slug).
 *
 * @package SmartImageMatcher\Compat
 * @since   3.1.4
 */

declare( strict_types=1 );

namespace SmartImageMatcher\Compat;

use SmartImageMatcher\AI\PromptBuilder;
use SmartImageMatcher\Settings\Settings;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class WpAiFeaturedImageCompat
 *
 * @since 3.1.4
 */
class WpAiFeaturedImageCompat {

	/**
	 * Register filters/actions when the WordPress AI plugin is present.
	 *
	 * @since 3.1.4
	 * @return void
	 */
	public function register(): void {
		if ( ! $this->isWpAiActive() ) {
			return;
		}

		add_filter( 'wpai_generated_image_filename', array( $this, 'filterFilename' ), 10, 2 );
		add_action( 'add_attachment', array( $this, 'normalizeAiAttachment' ), 20 );
	}

	/**
	 * Prefer focus keyword / post title for the upload basename.
	 *
	 * @since 3.1.4
	 * @param string               $filename Base filename without extension.
	 * @param array<string, mixed> $args     Import args from WP AI.
	 * @return string
	 */
	public function filterFilename( string $filename, array $args ): string {
		unset( $args );

		$post_id = $this->resolveEditingPostId();
		$title   = $this->resolvePreferredTitle( $post_id );
		if ( '' === $title ) {
			return $filename;
		}

		$slug = sanitize_title( $title );
		return ( '' !== $slug ) ? $slug : $filename;
	}

	/**
	 * After WP AI sideloads an AI image: attach to the post, fix title/slug/description/alt.
	 *
	 * @since 3.1.4
	 * @param int $attachment_id New attachment ID.
	 * @return void
	 */
	public function normalizeAiAttachment( int $attachment_id ): void {
		if ( $attachment_id <= 0 || ! wp_attachment_is_image( $attachment_id ) ) {
			return;
		}

		if ( 1 !== (int) get_post_meta( $attachment_id, 'ai_generated', true ) ) {
			return;
		}

		// Skip attachments SIM already owns.
		if ( get_post_meta( $attachment_id, '_sim_generated', true ) ) {
			return;
		}

		$post_id = $this->resolveEditingPostId();
		if ( $post_id <= 0 || ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}

		$title = $this->resolvePreferredTitle( $post_id );
		if ( '' === $title ) {
			$title = get_the_title( $post_id );
		}
		if ( '' === $title ) {
			return;
		}

		$attachment = get_post( $attachment_id );
		if ( ! $attachment instanceof \WP_Post ) {
			return;
		}

		$brief = $this->extractVisualBrief( (string) $attachment->post_content );

		$description = '';
		if ( Settings::get( 'ai_image_save_prompt_as_description' ) ) {
			$description = $brief;
		}

		$update = array(
			'ID'           => $attachment_id,
			'post_title'   => $title,
			'post_name'    => sanitize_title( $title ),
			'post_content' => $description,
			'post_parent'  => $post_id,
		);

		$author_id = (int) get_post_field( 'post_author', $post_id );
		if ( $author_id <= 0 ) {
			$author_id = (int) get_current_user_id();
		}
		if ( $author_id > 0 ) {
			$update['post_author'] = $author_id;
		}

		// phpcs:ignore WordPress.FAKESECRET_s1t2u3v4w5x6y7z8a9b0 -- intentional attachment metadata fix after WP AI import.
		wp_update_post( $update );

		$alt = $this->resolveAlt( $title, $brief );
		update_post_meta( $attachment_id, '_wp_attachment_image_alt', $alt );

		update_post_meta( $attachment_id, '_sim_generated', '1' );
		update_post_meta( $attachment_id, '_sim_generated_post_id', $post_id );
		update_post_meta( $attachment_id, '_sim_generated_keyword', PromptBuilder::getFocusKeyword( $post_id ) );
		if ( '' !== $brief ) {
			update_post_meta( $attachment_id, '_sim_generated_prompt', sanitize_textarea_field( $brief ) );
		}
		update_post_meta( $attachment_id, '_sim_generated_heading_hash', 'featured' );
	}

	/**
	 * Title-case focus keyword, else post title.
	 *
	 * @since 3.1.4
	 * @param int $post_id Post being edited.
	 * @return string
	 */
	private function resolvePreferredTitle( int $post_id ): string {
		if ( $post_id <= 0 ) {
			return '';
		}

		$keyword = PromptBuilder::getFocusKeyword( $post_id );
		$raw     = ( '' !== $keyword ) ? $keyword : (string) get_the_title( $post_id );
		$raw     = trim( wp_strip_all_tags( $raw ) );
		if ( '' === $raw ) {
			return '';
		}

		if ( function_exists( 'mb_convert_case' ) ) {
			return mb_convert_case( $raw, MB_CASE_TITLE, 'UTF-8' );
		}

		return ucwords( strtolower( $raw ) );
	}

	/**
	 * Strip WP AI’s “Generated by … Prompt:” wrapper; keep the visual brief.
	 *
	 * @since 3.1.4
	 * @param string $description Attachment post_content from WP AI.
	 * @return string
	 */
	private function extractVisualBrief( string $description ): string {
		$description = trim( $description );
		if ( '' === $description ) {
			return '';
		}

		if ( preg_match( '/\bPrompt:\s*(.+)$/is', $description, $matches ) ) {
			return sanitize_textarea_field( trim( $matches[1] ) );
		}

		// Drop the attribution line if present without a Prompt: suffix.
		if ( 0 === stripos( $description, 'Generated by ' ) ) {
			return '';
		}

		return sanitize_textarea_field( $description );
	}

	/**
	 * Alt text per SIM ai_image_alt_mode (keyword default).
	 *
	 * @since 3.1.4
	 * @param string $title Preferred title.
	 * @param string $brief Visual brief.
	 * @return string
	 */
	private function resolveAlt( string $title, string $brief ): string {
		$mode = (string) Settings::get( 'ai_image_alt_mode' );
		if ( 'descriptive' === $mode && '' !== $brief ) {
			// Keep a short descriptive sentence; avoid another AI call on the import hot path.
			$short = wp_html_excerpt( $brief, 125, '…' );
			return sanitize_text_field( $short );
		}

		return sanitize_text_field( $title );
	}

	/**
	 * Post ID from the editor referer (ability REST calls include it).
	 *
	 * @since 3.1.4
	 * @return int
	 */
	private function resolveEditingPostId(): int {
		$ref = wp_get_referer();
		if ( ! is_string( $ref ) || '' === $ref ) {
			if ( isset( $_SERVER['HTTP_REFERER'] ) ) {
				$ref = esc_url_raw( wp_unslash( (string) $_SERVER['HTTP_REFERER'] ) );
			}
		}

		if ( ! is_string( $ref ) || '' === $ref ) {
			return 0;
		}

		$query = wp_parse_url( $ref, PHP_URL_QUERY );
		if ( ! is_string( $query ) || '' === $query ) {
			return 0;
		}

		$args = array();
		wp_parse_str( $query, $args );

		return isset( $args['post'] ) ? absint( $args['post'] ) : 0;
	}

	/**
	 * @since 3.1.4
	 * @return bool
	 */
	private function isWpAiActive(): bool {
		if ( defined( 'WPAI_PLUGIN_FILE' ) || defined( 'WPAI_VERSION' ) ) {
			return true;
		}

		if ( ! function_exists( 'is_plugin_active' ) ) {
			require_once ABSPATH . 'wp-admin/includes/plugin.php';
		}

		return is_plugin_active( 'ai/ai.php' );
	}
}
